name: Testing PR CI


on:
  push:
#    branches: [main]
    branches: [testing_ci_pipeline]

jobs:
  test:
    name: Synpress Testing
#    if: github.ref == 'refs/heads/main' || || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Config yarn cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Env Var setup
        run: export SKIP_METAMASK_SETUP=true
      - name: Test Suite
        run: |
          yarn install --frozen-lockfile
          yarn run test

  # e2e:
  #   needs: build
  #   # run only on master/dev branch
  #   if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || github.event_name == 'pull_request'
  #   runs-on: ubuntu-latest

  #   container:
  #     image: ghcr.io/synthetixio/docker-e2e/ubuntu:14.17
  #     credentials:
  #       username: synthetixio
  #       password: ${{ secrets.GH_PACKAGES_READ_ONLY }}

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # pin@v2

  #     - name: Set npm cache directory
  #       run: npm config set cache .npm-cache --global
  #       continue-on-error: true

  #     - name: Cache node modules
  #       uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # pin@v2
  #       with:
  #         path: |
  #           .npm-cache
  #           node_modules
  #         key: ${{ runner.os }}-ubuntu-e2e-1-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-ubuntu-e2e-1-
  #       continue-on-error: true

  #     # fix: permission issues on ghactions+docker+npm@7
  #     - name: Chown workspace
  #       run: chown -R $(whoami) .

  #     - name: Install dependencies
  #       run: npm install --prefer-offline --no-audit
  #       env:
  #         CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/node_modules/.cache/Cypress

  #     - name: Run e2e tests
  #       run: npm run test:e2e:ci
  #       env:
  #         SKIP_METAMASK_SETUP: ${{ secrets.SKIP_METAMASK_SETUP }}
  #         CYPRESS_PRIVATE_KEY_WITH_FUNDS: ${{ secrets.CYPRESS_PRIVATE_KEY_WITH_FUNDS }}
  #         CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/node_modules/.cache/Cypress

  #     - name: Archive e2e artifacts
  #       uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # pin@v2
  #       if: always()
  #       with:
  #         name: e2e-artifacts
  #         path: |
  #           tests/e2e/videos
  #           tests/e2e/screenshots
  #       continue-on-error: true
